In [69]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import chi2
from sklearn.datasets import make_regression
from sklearn.ensemble import ExtraTreesClassifier
from scipy.stats import spearmanr

In [70]:
df = pd.read_csv('p2_mod.csv')

In [71]:
df.shape
df.head()

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  ...    X15    X16    X17  \
0   20000   2   2   1  24   2   2  -1  -1   -2  ...      0      0      0   
1  120000   2   2   2  26  -1   2   0   0    0  ...   3272   3455   3261   
2   90000   2   2   2  34   0   0   0   0    0  ...  14331  14948  15549   
3   50000   2   2   1  37   0   0   0   0    0  ...  28314  28959  29547   
4   50000   1   2   1  57  -1   0  -1   0    0  ...  20940  19146  19131   

    X18    X19    X20   X21   X22   X23  Y  
0     0    689      0     0     0     0  1  
1     0   1000   1000  1000     0  2000  1  
2  1518   1500   1000  1000  1000  5000  0  
3  2000   2019   1200  1100  1069  1000  0  
4  2000  36681  10000  9000   689   679  0  

[5 rows x 24 columns]

In [72]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [73]:
x= df.iloc[:,0:23].values

In [74]:
y= df.iloc[:,23].values

In [75]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
def run_randomForest(X_train, X_test, y_train, y_test):
    clf = RandomForestClassifier(n_estimators= 100, random_state = 0, n_jobs = -1)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print("Accuracy on Test Set: ")
    print(accuracy_score(y_test,y_pred))

In [76]:
run_randomForest(X_train, X_test, y_train, y_test)

Accuracy on Test Set: 
0.8156666666666667


In [77]:
print(x)

[[ 20000      2      2 ...      0      0      0]
 [120000      2      2 ...   1000      0   2000]
 [ 90000      2      2 ...   1000   1000   5000]
 ...
 [ 30000      1      2 ...   4200   2000   3100]
 [ 80000      1      3 ...   1926  52964   1804]
 [ 50000      1      2 ...   1000   1000   1000]]


In [78]:
print(y)

[1 1 0 ... 1 1 1]


In [79]:
forPCC= SelectKBest(score_func=f_regression, k=10)

In [80]:
XselforPCC= forPCC.fit_transform(x, y)
print(XselforPCC)
print(XselforPCC.shape)

[[ 20000      2      2 ...      0    689      0]
 [120000     -1      2 ...      0   1000   1000]
 [ 90000      0      0 ...   1518   1500   1000]
 ...
 [ 30000      4      3 ...      0      0   4200]
 [ 80000      1     -1 ...  85900   3409   1926]
 [ 50000      0      0 ...   2078   1800   1000]]
(30000, 10)


In [81]:
#col1=1
#counter=0
#cols=['c1','c2','c3','c4','c5','c6','c7','c8','c9','c10']
newdf=pd.DataFrame(XselforPCC)
print(newdf)

            0  1  2  3  4  5  6      7      8     9
0       20000  2  2 -1 -1 -2 -2      0    689     0
1      120000 -1  2  0  0  0  2      0   1000  1000
2       90000  0  0  0  0  0  0   1518   1500  1000
3       50000  0  0  0  0  0  0   2000   2019  1100
4       50000 -1  0 -1  0  0  0   2000  36681  9000
...       ... .. .. .. .. .. ..    ...    ...   ...
29995  220000  0  0  0  0  0  0   8500  20000  3047
29996  150000 -1 -1 -1 -1  0  0   1837   3526   129
29997   30000  4  3  2 -1  0  0      0      0  4200
29998   80000  1 -1  0  0  0 -1  85900   3409  1926
29999   50000  0  0  0  0  0  0   2078   1800  1000

[30000 rows x 10 columns]


In [82]:
newdf1=pd.DataFrame(y)

In [83]:
new_dataset = pd.concat([newdf, newdf1], axis=1)

In [84]:
print(new_dataset)

            0  1  2  3  4  5  6      7      8     9  0
0       20000  2  2 -1 -1 -2 -2      0    689     0  1
1      120000 -1  2  0  0  0  2      0   1000  1000  1
2       90000  0  0  0  0  0  0   1518   1500  1000  0
3       50000  0  0  0  0  0  0   2000   2019  1100  0
4       50000 -1  0 -1  0  0  0   2000  36681  9000  0
...       ... .. .. .. .. .. ..    ...    ...   ... ..
29995  220000  0  0  0  0  0  0   8500  20000  3047  0
29996  150000 -1 -1 -1 -1  0  0   1837   3526   129  0
29997   30000  4  3  2 -1  0  0      0      0  4200  1
29998   80000  1 -1  0  0  0 -1  85900   3409  1926  1
29999   50000  0  0  0  0  0  0   2078   1800  1000  1

[30000 rows x 11 columns]


In [85]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [86]:
from sklearn.model_selection import train_test_split

In [87]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

SVD

In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA, TruncatedSVD
svd = TruncatedSVD(n_components = 6)
svd.fit(X_train)
svd_X = svd.transform(X_train)

In [89]:
svd_X.shape

(24000, 6)

In [90]:
svd_X_train, svd_X_test, svd_y_train, svd_y_test = train_test_split(svd_X, y_train, test_size = 0.2, random_state = 42)

In [91]:
svd_lr = LinearRegression()

# Train the model
svd_model = svd_lr.fit(svd_X_train, svd_y_train)

# Prediction
pca_y_pred =  svd_lr.predict(svd_X_test)

# Accuracy Score
svd_lr.score(svd_X_test, pca_y_pred)

1.0

SVM

In [92]:
from sklearn import svm
from sklearn.svm import SVC

In [93]:
svm = svm.SVC()
svm.fit(svd_X_train, svd_y_train)
svm.score(svd_X_train, svd_y_train)*100

77.88020833333333

In [94]:
svm_score = svm.score(svd_X_test, svd_y_test)*100
print("SVM Accuracy:", svm_score)

SVM Accuracy: 77.60416666666666


knn

In [95]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier()
classifier = KNeighborsClassifier(n_neighbors = 81)
classifier.fit(svd_X_train, svd_y_train)
knn.fit(svd_X_train, svd_y_train)

KNeighborsClassifier()

In [96]:
score = knn.score(svd_X_test, svd_y_test)
print("KNN Algorithm Score:", score*100)

KNN Algorithm Score: 75.25


DT

In [97]:
from sklearn.tree import DecisionTreeClassifier
dclf = DecisionTreeClassifier()
dclf.fit(svd_X_train, svd_y_train)

DecisionTreeClassifier()

In [98]:
j=dclf.score(svd_X_test, svd_y_test)
print("Decision Tree Algorithm Score:",j*100)

Decision Tree Algorithm Score: 68.04166666666667


RF

In [99]:
def run_randomForest(svd_X_train, svd_y_train,svd_X_test, svd_y_test):
    clf = RandomForestClassifier(n_estimators= 100, random_state = 42, n_jobs = -1)
    clf.fit(svd_X_train, svd_y_train)
    y_pred = clf.predict(svd_X_test)
    score = accuracy_score(svd_y_test,y_pred)*100
    print("Random Forest Accuracy:", score)

In [100]:
run_randomForest(svd_X_train, svd_y_train,svd_X_test, svd_y_test)

Random Forest Accuracy: 77.5625


LR

In [101]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(svd_X_train, svd_y_train)
lr = model.score(svd_X_test, svd_y_test)*100
print("Logistic Regression Accuracy:", lr)

Logistic Regression Accuracy: 77.60416666666666
